name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up Python 3.10
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.10"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0

      - name: Install dependencies
        run: uv sync

      - name: Setup etcd
        uses: supplypike/setup-bin@8365380a806a88e7a0f0d07059b175ca2f5418d7 # v5.0.1
        with:
          uri: "https://github.com/etcd-io/etcd/releases/download/v3.6.6/etcd-v3.6.6-linux-amd64.tar.gz"
          name: "etcd"
          version: "3.6.6"
          subPath: "etcd-v3.6.6-linux-amd64"

      - name: Setup etcdutl
        uses: supplypike/setup-bin@8365380a806a88e7a0f0d07059b175ca2f5418d7 # v5.0.1
        with:
          uri: "https://github.com/etcd-io/etcd/releases/download/v3.6.6/etcd-v3.6.6-linux-amd64.tar.gz"
          name: "etcdutl"
          version: "3.6.6"
          subPath: "etcd-v3.6.6-linux-amd64"

      - name: Setup etcdctl
        uses: supplypike/setup-bin@8365380a806a88e7a0f0d07059b175ca2f5418d7 # v5.0.1
        with:
          uri: "https://github.com/etcd-io/etcd/releases/download/v3.6.6/etcd-v3.6.6-linux-amd64.tar.gz"
          name: "etcdctl"
          version: "3.6.6"
          subPath: "etcd-v3.6.6-linux-amd64"

      - name: Test all etcd tools
        run: |
          etcdctl --help
          etcdutl --help
          etcd --help

      - name: Install tox
        run: uv tool install tox --with tox-uv

      - name: Run proto generation
        run: tox run -e genproto

      - name: Run lint
        run: tox run -e ruff

      - name: Run test
        run: tox run -e py310
